language: cpp

os:
  - linux
  - osx

addons:
  mariadb: '10.1'

install:
  # For our forks that do not have mult-os enabled...
  - if [ -z "${TRAVIS_OS_NAME}" ]; then
    export TRAVIS_OS_NAME=linux;
    fi
  # Install dependencies
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        sudo apt-get update -qq;
        sudo apt-get install zlib1g-dev libgc-dev -qq;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew tap homebrew/dupes;
        brew update;
        brew install bdw-gc pcre openssl zlib mariadb;
        brew link zlib --force;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        make;
        make test;
        sudo make install;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        make os=osx LIB_PREFIX=/usr/local;
        make test;
        sudo make os=osx install;
    fi
  - neko -version
  - neko src/tools/test.n
  - nekoc src/benchs/ackerman.neko && neko src/benchs/ackerman
  - nekoc src/benchs/binary-trees.neko && neko src/benchs/binary-trees
  - nekoc src/benchs/fannkuch.neko && neko src/benchs/fannkuch
  - nekoc src/benchs/fib.neko && neko src/benchs/fib
  - nekoc src/benchs/fp.neko && neko src/benchs/fp
  - nekoc src/benchs/module.neko && neko src/benchs/module
  - nekoc src/benchs/nbodies.neko && neko src/benchs/nbodies
  - nekoc src/benchs/nsieve.neko && neko src/benchs/nsieve
  - nekoc src/benchs/recursive.neko && neko src/benchs/recursive
  - nekoc src/benchs/startup.neko && neko src/benchs/startup
  - nekoc src/benchs/test_ops.neko && neko src/benchs/test_ops

